name: squadre
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.2.3595
  speech_bubble: ^0.0.5
  firebase_core: ^0.3.4
  fluttertoast: ^3.0.3
  firebase_database: ^2.0.2
  firebase_auth: ^0.8.4+5
  shared_preferences: ^0.5.1+1
  image_picker: ^0.5.3+1
  path_provider: ^0.5.0+1
  permission_handler: ^3.0.0
  firebase_storage: ^2.1.1+1
  rxdart: ^0.21.0
  flutter_facebook_login: ^2.0.0
  dio: ^2.1.2
  http: ^0.12.0+2
  google_sign_in: ^4.0.1+3
  flutter_advanced_networkimage: ^0.4.15
  intl: ^0.15.8
  countdown: ^0.1.0
  file_picker: ^1.3.4+1
  uuid: ^2.0.1
  video_player: ^0.10.0+8
  cached_network_image: ^0.7.0
  firebase_performance: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/fb.png
  - assets/images/google.png
  - assets/images/twitter.png
  - assets/images/linked.png
  - assets/images/alphabet.png
  - assets/images/cortana.png
  - assets/images/football.png
  - assets/images/team1.png
  - assets/images/people.png
  - assets/images/splash.png
  - assets/images/cortana.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
  - family: CalibreMedium
    fonts:
    - asset: assets/fonts/CalibreMedium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
